### ISSUE TITLE
"is not a valid Git directory" in a valid Git directory

### ISSUE THREAD

**Issue by HoutarouOreki** [vmf91/git-time#4]
![image](https://user-images.githubusercontent.com/16261733/102266423-b433f100-3f18-11eb-9e9c-ae52f42645e2.png)
git-time version 1.0.6
git version 2.17.1.windows.2

**Comment by bitsnaps** [comment]
Try to use it from the outside of the directory, it worked for me.

**Comment by vmf91** [comment]
Solved on version 1.0.7.
